### PR TITLE
Some readme fixes

### PR DESCRIPTION
**Pull request by adriaanvanrossum**
Thanks for this module. I really love it, coming from front end development.

### CODE REVIEW

**Comment by adriaanvanrossum** [comment]
cc @simonlast

**Comment by akhoury** [comment]
@adriaanvanrossum I'm also a maintainer of this module, would you mind replying to the review comments I added

**Comment by adriaanvanrossum** [comment]
I don't see any?

**Comment by adriaanvanrossum** [comment]
Ping @akhoury

**Comment by akhoury** [comment]
for some reason my comments are "pending"? not sure why, @simonlast ? 

Anyways, here are screenshots of them.

# comment-1

Screen Shot 2019-08-04 at 5 37 50 PM

# comment-2

Screen Shot 2019-08-04 at 5 38 03 PM

**Comment by adriaanvanrossum** [comment]
If you review is pending you need to submit your review.

Here is explained how you can do this: https://help.github.com/en/articles/reviewing-proposed-changes-in-a-pull-request#submitting-your-review

**Comment by adriaanvanrossum** [comment]
Too late.

**Pull request closed without merging**
