### PR TITLE
Closes simonlast/node-persist#76

### PR DESCRIPTION
**Pull request by noahtkeller**
modified:   src/local-storage.js

* Call interval.unref() after setting interval

### CODE REVIEW

**Comment by akhoury** [comment]
HA! this is awesome! thanks @noahtkeller

**Comment by noahtkeller** [comment]
You're welcome, glad I could contribute.

**Comment by danielerescigno-freedompro** [comment]
Hello everyone!
When I run my app that executes this code 

`$(document).ready(function () {
    var storage = require('node-persist');
    
    storage.init({
        logging: true
    }).then(function () {
        storage.getItem('shutter', function (err, value) {
            console.log(value);
        });
    });
});`

I can see this error string: `Uncaught TypeError: this._expiredKeysInterval.unref is not a function`.

If I comment `this._expiredKeysInterval.unref();` (line 689 in src/local-storage.js) everything well done.

Why?

Thanks,
Daniele R.

**Comment by danielerescignopersonal** [comment]
Hello everyone!
When I run my app that executes this code 

`  var storage = require('node-persist');    
    storage.init({
        logging: true
    }).then(function () {
        storage.getItem('shutter', function (err, value) {
            console.log(value);
        });
    });
`

I can see this error string: `Uncaught TypeError: this._expiredKeysInterval.unref is not a function`.

If I comment `this._expiredKeysInterval.unref();` (line 689 in src/local-storage.js) everything well done.

Why?

Thanks,
Daniele R.

**Comment by akhoury** [comment]
what is your node version?
```
node -v
```

**Comment by danielerescignopersonal** [comment]
Hello AKhoury,
my node version is v7.8.0 .

Many thanks,
Daniele

**Comment by akhoury** [comment]
can u tell me exactly how are you executing this code? are you putting them in file then running `node file`?

**Comment by danielerescignopersonal** [comment]
Ok, steps are:
1) run `npm start`
2) that starts electron app in which there is the following code:

`/*
 * Storage (node-persist)
 */

var storage = require('node-persist'),
    device = {};

storage.init({
    logging: true
}).then(function () {
    storage.getItem('device', function (err, value) {
        if (err) throw err;
        if (!value) {
            fs.readFile('deviceDefaultStructure.json', 'utf8', (err, deviceDefaultStructure) => {
                if (err) throw err;

                storage.setItem("device", JSON.parse(deviceDefaultStructure), function (err) {
                    if (err) throw err;

                    device = JSON.parse(deviceDefaultStructure);
                    loadApplication();
                });
            });
        } else {
            device = value;
            loadApplication();
        }
    });
});`

3) this returns error code in electron console
`Uncaught TypeError: this._expiredKeysInterval.unref is not a function
   at LocalStorage.startExpiredKeysInterval (path/to/node_modules/node-persist/src/local-storage.js:689:35)
   at LocalStorage.init (path/to/node_modules/node-persist/src/local-storage.js:113:18)
   at Object.nodePersist.init (path/to/node_modules/node-persist/src/node-persist.js:27:32)
   at file that contains code above`

Daniele R.

**Comment by akhoury** [comment]
maybe relevant 
https://github.com/watson/bonjour/issues/23
https://github.com/tapjs/node-tap/issues/347

I believe electron is executing this code on the client-side, where timers don't have have the `unref` function available. I can fix this.

**Comment by akhoury** [comment]
fixed, try this version [`node-persist@2.0.11`](https://www.npmjs.com/package/node-persist)

**Comment by danielerescignopersonal** [comment]
Hello AKhoury,
issue solved!

Thanks,
Daniele R.

**Pull request merged**
