### PR TITLE
ignore (weird) parsing error

### PR DESCRIPTION
**Pull request by jessevdp**
Parsing error when unexpected files live in the cache folder is now ignored unless in 'safemode'. Which is an option I just made up...

This seems to do it, I lightly tested it and turning safemode on and off does make a difference, I don't know if my code is the easiest/best way to do this. I simply don't know the repository well enough for this.

I tried, hope this works!

See #72 for more details.

### CODE REVIEW

**Comment by akhoury** [comment]
@skillzzjesse thanks for this.

I don't think the `safemode` option is necessary. Ignoring files we can't parse sounds like a fair feature to be enabled - as someone or something else could potentially use the storage for something else. i.e. adding a `.gitignore` in there. 

Also, adding a new option like `safemode` opens up more work, as we would then have to handle it in many other places where errors could occur, not just parse error, So I think we should remove the `safemode` option, otherwise we would have to deal with it everywhere.

I say, just add the ignore error logic without the `safemode` option.

The other thing is that `.parse()` function gets called in both `parseFile` and `parseFileSync`, but you only handled the `parseFile` one. 

Finally, now that I think about it, i think we shouldn't use a `try/catch` in the `.parse()` function, just it throw the error, and we should just catch it in [`parseStorageDir`](https://github.com/simonlast/node-persist/blob/7d39f9e031f95d84bc07c2164eea51bb7e76026f/src/local-storage.js#L560) (and[`parseStorageDirSync`](https://github.com/simonlast/node-persist/blob/7d39f9e031f95d84bc07c2164eea51bb7e76026f/src/local-storage.js#L602)) and check the error and decide to ignore it there - since we would only want to forgive parsing a directory of files, but if someone is using the `parseFile` api function to parse a file, an error should be thrown if the file cannot be parsed.

So next steps IMO should be

- remove the try/catch from `parse`
- handle the error in both `parseStorageDir` and `parseStorageDirSync`

let me know if you want to take a shot at it or I could.

Thanks

**Comment by skillzzjesse** [comment]
Are you sure we should remove the try catch block? 

`parseFile` uses `self.parse`. However that function will throw. We could instead return something like the phrase 'ERROR' from within this function. And then handle this string within `parseFile`, rejecting the promise called `deferred`.

Or we could remove the `try {} catch {}` block down in `parse` and move it up to `parseFile` or possibly even higher? 

```js
try {
  self.parseFile(...)  || self.parseFileSync(...)
} catch (e) {
// Ignore this file
}
```

**I do think ignoring a file is easier trough an `if/else` statement** 
```js
var foo = self.parseFile(...)  || self.parseFileSync(...)
if (foo === "SOME_ERROR") {
  // Igonre the file
} else {
  // Handle the file
}
```

----
_I'm not quite sure how all these promise like thing work in this particular project. So most things I say are a result pure guesswork. (when it comes to the promises)_

**Comment by skillzzjesse** [comment]
I really don't get how I see both `resolve()` and `callback(null, data)` everywhere. Right next to each other. It seems off to me. But then again, I'm fairly new to promises in general. And these promises seem different too.

Anyway, as long as it works 👍 😄

**Comment by skillzzjesse** [comment]
As you can see I pushed another commit to this PR. I think I did what was necessary but i'm not completely sure. Perhaps you should look into the code yourself? (since you know what's going on in the code and stuff.) 

---
_Sidenote: I didn't have time to run tests on this yet myself, I think this is litteraly the most derpy commit I've ever done 😂_

**Comment by akhoury** [comment]
closing this as I added `forgiveParseErrors` which is specific to parsing, not a general `safemode` - also added tests, i can't accept PR without test coverage

**Pull request closed without merging**
